services:

  web:
    build: .
    container_name: django
    restart: always

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn biblioteca.wsgi:application --bind 0.0.0.0:8000
      "

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot

    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
volumes:
  static_volume:
  media_volume:
